<a href="https://colab.research.google.com/github/amirValiulla32/MPower-Hackathon/blob/main/notebooks/01_data_eac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Libraries

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive

Dataset Linking

In [10]:
drive.mount('/content/drive')
PATH_DATA_2 = "/content/drive/MyDrive/ISOC-hackathon/data/data_2_og_25-100.csv"
PATH_DATA_1 = "/content/drive/MyDrive/ISOC-hackathon/data/data_1_og_1-25.csv"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
dataset_1 = pd.read_csv(PATH_DATA_1)
dataset_2 = pd.read_csv(PATH_DATA_2)

/tmp/ipython-input-1527365983.py:1: DtypeWarning: Columns (13,29) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset_1 = pd.read_csv(PATH_DATA_1)
/tmp/ipython-input-1527365983.py:2: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset_2 = pd.read_csv(PATH_DATA_2)

In [16]:
dataset_1.head()

,Voter File VANID,StateFileID,VendorID,LastName,FirstName,MiddleName,Age Range,Sex,Zip5,Zip4,...,AfricanAmerican,Hispanic,NativeAmerican,Caucasian,Asian,Jewish,Mormon,NonRelig,TMC_LABEL,TRUTH LABEL
0,5689102,243806,CA-000006816630,Tylner,Sam,NaN,75-80,M,92691,3708.0,...,0.9,15.2,0.8,39.6,43.5,66.3,33,29.4,0,NaN
1,6387707,404220,CA-000007611945,Yasnogorodsky,Vitaly,NaN,50-55,M,90740,5737.0,...,1.0,13.9,1.0,77.8,6.3,73.7,56.7,29.2,0,NaN
2,25518976,13368971,CA-27664438,Alkhamis,Bassam,NaN,40-45,M,92629,5201.0,...,4.6,60.9,0.0,28.7,5.8,32.4,8.9,70.8,0,NaN
3,35442831,17522629,CA-42526332,Winer,Lilya,Kirzhner,50-55,F,92602,1657.0,...,0.2,1.4,0.9,82.7,14.9,77.7,60.7,30.9,0,NaN
4,5596003,440145,CA-36625763,Dinh,Dunes,NaN,60-65,M,92806,5014.0,...,0.1,4.9,2.2,0.6,92.2,52.6,47.9,43.0,0,NaN

In [19]:
dataset_2.head()

,Voter File VANID,StateFileID,VendorID,CountyFileID,LastName,FirstName,MiddleName,Suffix,Age Range,Sex,...,AfricanAmerican,Hispanic,NativeAmerican,Caucasian,Asian,Jewish,Mormon,NonRelig,TMC_Label,TRUTH_LABEL
0,55796349,43551638,CA-51219716,NaN,Banu,Laila,Arjumand,NaN,60-65,F,...,0.0,0.2,0.4,6.6,92.8,58.5,15.5,67.9,1.0,#REF!
1,55777186,36580759,CA-41098276,NaN,Hasan,Aiman,NaN,NaN,20-25,U,...,3.0,0.8,0.1,4.3,91.8,44.6,6.7,51.5,1.0,#REF!
2,46709577,29515440,CA-29064941,527288734.0,Mohammed,Wafa,Abdelmagid,NaN,35-40,F,...,4.4,2.0,0.2,2.5,91.0,64.7,15.9,40.0,1.0,#REF!
3,13962358,915555,CA-17041079,3055381.0,Abdullah,Maryam,NaN,NaN,45-50,F,...,4.7,3.9,0.4,8.0,82.9,43.7,14.2,73.3,1.0,#REF!
4,10094550,660743,CA-000012137986,2455701.0,Aziz,Zermina,NaN,NaN,45-50,F,...,0.6,0.9,0.1,7.4,91.0,66.7,16.8,51.5,1.0,#REF!

In [24]:
print("Dataset 1: ")
dataset_1.info()
print("\nDataset 2: ")
dataset_2.info()

Dataset 1:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128892 entries, 0 to 128891
Data columns (total 33 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Voter File VANID            128892 non-null  int64
 1   StateFileID                 128892 non-null  int64
 2   VendorID                    128892 non-null  object
 3   LastName                    128892 non-null  object
 4   FirstName                   128880 non-null  object
 5   MiddleName                  76281 non-null   object
 6   Age Range                   128892 non-null  object
 7   Sex                         128892 non-null  object
 8   Zip5                        128892 non-null  int64
 9   Zip4                        128707 non-null  float64
 10  Congressional District      128892 non-null  int64
 11  Senate District             128892 non-null  int64
 12  Preferred Phone             119405 non-null  float64
 13  Preferred Language          13709 non-null   object
 14  RaceName                    128892 non-null  object
 15  muslim score                128892 non-null  float64
 16  Harris Supporter            114926 non-null  float64
 17  Campaign finance supporter  111840 non-null  float64
 18  Climate Change Supporter    116070 non-null  float64
 19  College Grad                128108 non-null  float64
 20  Pro Gun Ownership           119956 non-null  float64
 21  HomeOwner                   127848 non-null  float64
 22  UnionSupport                123739 non-null  float64
 23  AfricanAmerican             115938 non-null  float64
 24  Hispanic                    115938 non-null  float64
 25  NativeAmerican              115938 non-null  float64
 26  Caucasian                   115938 non-null  float64
 27  Asian                       115938 non-null  float64
 28  Jewish                      119813 non-null  float64
 29  Mormon                      119813 non-null  object
 30  NonRelig                    119813 non-null  float64
 31  TMC_LABEL                   128892 non-null  int64
 32  TRUTH LABEL                 23 non-null      float64
dtypes: float64(18), int64(6), object(9)
memory usage: 32.5+ MB

Dataset 2:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32046 entries, 0 to 32045
Data columns (total 35 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Voter File VANID         32046 non-null  int64
 1   StateFileID              32046 non-null  int64
 2   VendorID                 32046 non-null  object
 3   CountyFileID             17272 non-null  float64
 4   LastName                 32046 non-null  object
 5   FirstName                32046 non-null  object
 6   MiddleName               16638 non-null  object
 7   Suffix                   81 non-null     object
 8   Age Range                32046 non-null  object
 9   Sex                      32046 non-null  object
 10  Zip5                     32046 non-null  int64
 11  Zip4                     32012 non-null  float64
 12  AddressID                32046 non-null  int64
 13  Congressional District   32046 non-null  int64
 14  Senate District          32046 non-null  int64
 15  Preferred Phone          29281 non-null  float64
 16  Preferred Language       161 non-null    object
 17  RaceName                 32046 non-null  object
 18  muslim                   32046 non-null  float64
 19  Campaign Finance Reform  27639 non-null  float64
 20  Pro Climate Change       28678 non-null  float64
 21  College Grad             31831 non-null  float64
 22  Pro Gun Ownership        29712 non-null  float64
 23  HomeOwner                31774 non-null  float64
 24  UnionSupport             30671 non-null  float64
 25  AfricanAmerican          28743 non-null  float64
 26  Hispanic                 28743 non-null  float64
 27  NativeAmerican           28743 non-null  float64
 28  Caucasian                28743 non-null  float64
 29  Asian                    28743 non-null  float64
 30  Jewish                   29679 non-null  float64
 31  Mormon                   29679 non-null  float64
 32  NonRelig                 29679 non-null  float64
 33  TMC_Label                32045 non-null  float64
 34  TRUTH_LABEL              297 non-null    object
dtypes: float64(19), int64(6), object(10)
memory usage: 8.6+ MB

In [27]:
dataset_1.isnull().sum()

Voter File VANID                   0
StateFileID                        0
VendorID                           0
LastName                           0
FirstName                         12
MiddleName                     52611
Age Range                          0
Sex                                0
Zip5                               0
Zip4                             185
Congressional District             0
Senate District                    0
Preferred Phone                 9487
Preferred Language            115183
RaceName                           0
muslim score                       0
Harris Supporter               13966
Campaign finance supporter     17052
Climate Change Supporter       12822
College Grad                     784
Pro Gun Ownership               8936
HomeOwner                       1044
UnionSupport                    5153
AfricanAmerican                12954
Hispanic                       12954
NativeAmerican                 12954
Caucasian                      12954
Asian                          12954
Jewish                          9079
Mormon                          9079
NonRelig                        9079
TMC_LABEL                          0
TRUTH LABEL                   128869
dtype: int64

In [28]:
dataset_2.isnull().sum()

Voter File VANID               0
StateFileID                    0
VendorID                       0
CountyFileID               14774
LastName                       0
FirstName                      0
MiddleName                 15408
Suffix                     31965
Age Range                      0
Sex                            0
Zip5                           0
Zip4                          34
AddressID                      0
Congressional District         0
Senate District                0
Preferred Phone             2765
Preferred Language         31885
RaceName                       0
muslim                         0
Campaign Finance Reform     4407
Pro Climate Change          3368
College Grad                 215
Pro Gun Ownership           2334
HomeOwner                    272
UnionSupport                1375
AfricanAmerican             3303
Hispanic                    3303
NativeAmerican              3303
Caucasian                   3303
Asian                       3303
Jewish                      2367
Mormon                      2367
NonRelig                    2367
TMC_Label                      1
TRUTH_LABEL                31749
dtype: int64